/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianObjectsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  templateFolder: "Templates",
  triggerTemplates: [
    { trigger: "@project", templateName: "project", outputPath: "Projects/", enabled: true },
    { trigger: "@atomic", templateName: "atomic", outputPath: "Zettelkasten/", enabled: true },
    { trigger: "@person", templateName: "person", enabled: true }
  ],
  defaultOutputPath: ""
};
var SettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.debouncedSave = (0, import_obsidian.debounce)(() => this.plugin.saveSettings(), 500, true);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian Objects Settings" });
    const isTemplaterActive = !!this.plugin.templater.getApi();
    new import_obsidian.Setting(containerEl).setName("Integrations Status").setDesc(isTemplaterActive ? "Templater integration is active." : "WARNING: Templater plugin is not detected.").then((s) => {
      const status = s.controlEl.createSpan({
        text: isTemplaterActive ? "\u2714 Active" : "\u2718 Missing"
      });
      status.style.fontWeight = "bold";
      status.style.color = isTemplaterActive ? "var(--text-success)" : "var(--text-error)";
    });
    containerEl.createEl("h3", { text: "General Configuration" });
    new import_obsidian.Setting(containerEl).setName("Template Folder").setDesc("Root directory for your markdown templates.").addText((text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templateFolder).onChange((v) => {
      this.plugin.settings.templateFolder = v;
      this.debouncedSave();
    }));
    new import_obsidian.Setting(containerEl).setName("Default Output Path").setDesc("Fallback folder for newly created notes.").addText((text) => text.setPlaceholder("Inbox/").setValue(this.plugin.settings.defaultOutputPath).onChange((v) => {
      this.plugin.settings.defaultOutputPath = v;
      this.debouncedSave();
    }));
    containerEl.createEl("h3", { text: "Trigger Mappings" });
    this.plugin.settings.triggerTemplates.forEach((mapping, index) => {
      const s = new import_obsidian.Setting(containerEl).addToggle((t) => t.setValue(mapping.enabled).onChange(async (v) => {
        mapping.enabled = v;
        await this.plugin.saveSettings();
      })).addText((t) => t.setPlaceholder("@trigger").setValue(mapping.trigger).onChange((v) => {
        mapping.trigger = v.startsWith("@") ? v : v ? "@" + v : "@";
        t.setValue(mapping.trigger);
        this.debouncedSave();
      })).addText((t) => {
        new TemplateSuggest(this.app, t.inputEl, this.plugin);
        t.setPlaceholder("Template").setValue(mapping.templateName).onChange((v) => {
          mapping.templateName = v.replace(/\.md$/, "");
          this.debouncedSave();
        });
      }).addText((t) => t.setPlaceholder("Target Folder").setValue(mapping.outputPath || "").onChange((v) => {
        mapping.outputPath = v;
        this.debouncedSave();
      })).addExtraButton((b) => b.setIcon("trash").setTooltip("Delete Mapping").onClick(async () => {
        this.plugin.settings.triggerTemplates.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      }));
      s.infoEl.remove();
      s.settingEl.style.borderTop = "none";
      s.controlEl.style.width = "100%";
      s.controlEl.style.display = "flex";
      s.controlEl.style.gap = "10px";
      s.controlEl.style.justifyContent = "space-between";
      s.controlEl.querySelectorAll('input[type="text"]').forEach((el) => {
        el.style.flex = "1 1 0";
        el.style.minWidth = "80px";
      });
    });
    new import_obsidian.Setting(containerEl).addButton((btn) => btn.setButtonText("Add New Mapping").setCta().onClick(async () => {
      this.plugin.settings.triggerTemplates.push({ trigger: "@", templateName: "", enabled: true });
      await this.plugin.saveSettings();
      this.display();
    }));
    const footer = containerEl.createDiv();
    footer.style.marginTop = "4rem";
    footer.style.textAlign = "center";
    footer.style.color = "var(--text-muted)";
    footer.style.fontSize = "var(--font-ui-smaller)";
    footer.textContent = "Settings are saved automatically. Triggers must start with @.";
  }
};
var TemplateSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, plugin) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.plugin = plugin;
  }
  getSuggestions(query) {
    const root = this.plugin.settings.templateFolder;
    if (!root)
      return [];
    const lower = query.toLowerCase();
    return this.app.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(root + "/") && f.path.toLowerCase().includes(lower)
    );
  }
  renderSuggestion(file, el) {
    const root = this.plugin.settings.templateFolder;
    const rel = file.path.startsWith(root + "/") ? file.path.substring(root.length + 1) : file.path;
    el.setText(rel.replace(/\.md$/, ""));
  }
  selectSuggestion(file) {
    const root = this.plugin.settings.templateFolder;
    const rel = file.path.startsWith(root + "/") ? file.path.substring(root.length + 1) : file.path;
    this.inputEl.value = rel.replace(/\.md$/, "");
    this.inputEl.dispatchEvent(new Event("input"));
    this.inputEl.dispatchEvent(new Event("change"));
    this.close();
  }
};

// src/templater.ts
var import_obsidian2 = require("obsidian");
var TemplaterHandler = class {
  constructor(app) {
    this.app = app;
  }
  getApi() {
    const plugins = this.app.plugins;
    if (!plugins || !plugins.enabledPlugins.has("templater-obsidian")) {
      return null;
    }
    const plugin = plugins.plugins["templater-obsidian"];
    return (plugin == null ? void 0 : plugin.templater) || null;
  }
  async createNoteFromTemplate(templateFile, folderPath, fileName) {
    const api = this.getApi();
    const newNotePath = (0, import_obsidian2.normalizePath)(folderPath ? `${folderPath}/${fileName}.md` : `${fileName}.md`);
    if (api && templateFile) {
      return await api.create_new_note_from_template(templateFile, folderPath, fileName, false);
    } else {
      console.log("Obsidian Objects: Using internal placeholder logic.");
      let content = "";
      if (templateFile instanceof import_obsidian2.TFile) {
        content = await this.app.vault.read(templateFile);
        content = this.replacePlaceholders(content, fileName);
      }
      return await this.app.vault.create(newNotePath, content);
    }
  }
  replacePlaceholders(content, title) {
    const now = window.moment();
    const date = now.format("YYYY-MM-DD");
    const time = now.format("HH:mm");
    return content.replace(/\{\{title\}\}/g, title).replace(/\{\{date\}\}/g, date).replace(/\{\{time\}\}/g, time);
  }
};

// src/suggester.ts
var import_obsidian4 = require("obsidian");

// src/modal.ts
var import_obsidian3 = require("obsidian");
var TitleModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, targetFolder, onSubmit) {
    super(app);
    this.result = "";
    this.plugin = plugin;
    this.targetFolder = targetFolder;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter Note Title" });
    const setting = new import_obsidian3.Setting(contentEl).setName("Title").addText((text) => {
      text.setPlaceholder("My new note").setValue(this.result).onChange((value) => {
        this.result = value;
      });
      new FileSuggest(this.app, text.inputEl, this.plugin, this.targetFolder);
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          if (e.key === "Enter") {
            setTimeout(() => {
              if (this.app.workspace.activeLeaf) {
                this.submit();
              }
            }, 100);
          }
        }
      });
      setTimeout(() => text.inputEl.focus(), 0);
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create / Link").setCta().onClick(() => {
        this.submit();
      })
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    );
  }
  submit() {
    if (this.result && this.result.trim().length > 0) {
      this.onSubmit(this.result.trim());
      this.close();
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var FileSuggest = class extends import_obsidian3.AbstractInputSuggest {
  constructor(app, inputEl, plugin, targetFolder) {
    super(app, inputEl);
    this.plugin = plugin;
    this.targetFolder = targetFolder;
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const lowerCaseQuery = query.toLowerCase();
    const files = this.app.vault.getMarkdownFiles();
    const normalizedTarget = this.targetFolder ? this.targetFolder.replace(/\/$/, "") : "";
    return files.filter((file) => {
      const folderPath = file.parent ? file.parent.path : "";
      const isInFolder = normalizedTarget === "" || folderPath === normalizedTarget;
      const matchesQuery = file.basename.toLowerCase().includes(lowerCaseQuery);
      return isInFolder && matchesQuery;
    }).slice(0, 10);
  }
  renderSuggestion(file, el) {
    el.setText(file.basename);
  }
  selectSuggestion(file) {
    this.inputEl.value = file.basename;
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/suggester.ts
var TriggerSuggest = class extends import_obsidian4.EditorSuggest {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onTrigger(cursor, editor) {
    const line = editor.getLine(cursor.line).substring(0, cursor.ch);
    const match = line.match(/(?:^|\s)@(\w*)$/);
    if (match) {
      const query = match[1];
      const triggerStart = line.length - (query.length + 1);
      return {
        start: { line: cursor.line, ch: triggerStart },
        end: cursor,
        query
      };
    }
    return null;
  }
  getSuggestions(context) {
    const query = context.query.toLowerCase();
    return this.plugin.settings.triggerTemplates.filter(
      (t) => t.enabled && t.trigger.toLowerCase().startsWith("@" + query)
    );
  }
  renderSuggestion(suggestion, el) {
    el.setText(suggestion.trigger);
  }
  async selectSuggestion(suggestion, evt) {
    var _a;
    const context = this.context;
    if (!context)
      return;
    const editor = context.editor;
    const folder = (_a = suggestion.outputPath) != null ? _a : this.plugin.settings.defaultOutputPath;
    const finalFolderPath = folder ? (0, import_obsidian4.normalizePath)(folder) : "";
    new TitleModal(this.app, this.plugin, finalFolderPath, async (title) => {
      await this.createNote(suggestion, title, context, editor);
    }).open();
  }
  async createNote(suggestion, title, context, editor) {
    var _a;
    const sanitizedTitle = title.replace(/[\\/:"*?<>|]/g, "_");
    const folder = (_a = suggestion.outputPath) != null ? _a : this.plugin.settings.defaultOutputPath;
    const finalFolderPath = folder ? (0, import_obsidian4.normalizePath)(folder) : "";
    const newNotePath = (0, import_obsidian4.normalizePath)(finalFolderPath ? `${finalFolderPath}/${sanitizedTitle}.md` : `${sanitizedTitle}.md`);
    const existingFile = this.app.vault.getAbstractFileByPath(newNotePath);
    const activeFile = this.app.workspace.getActiveFile();
    const sourcePath = activeFile ? activeFile.path : "";
    if (existingFile instanceof import_obsidian4.TFile) {
      let link = this.app.fileManager.generateMarkdownLink(existingFile, sourcePath, "", title);
      link = link.trim();
      editor.focus();
      editor.replaceRange(link, context.start, context.end);
      editor.setCursor({
        line: context.start.line,
        ch: context.start.ch + link.length
      });
      new import_obsidian4.Notice(`Linked to existing note: "${existingFile.basename}"`);
      return;
    }
    const templatePath = (0, import_obsidian4.normalizePath)(`${this.plugin.settings.templateFolder}/${suggestion.templateName}.md`);
    const templateFile = this.app.vault.getAbstractFileByPath(templatePath);
    const templaterApi = this.plugin.templater.getApi();
    if (templaterApi && !(templateFile instanceof import_obsidian4.TFile)) {
      new import_obsidian4.Notice(`Template "${templatePath}" not found.`, 4e3);
      return;
    }
    try {
      if (finalFolderPath && !this.app.vault.getAbstractFileByPath(finalFolderPath)) {
        await this.app.vault.createFolder(finalFolderPath);
      }
      const newFile = await this.plugin.templater.createNoteFromTemplate(
        templateFile instanceof import_obsidian4.TFile ? templateFile : null,
        finalFolderPath,
        sanitizedTitle
      );
      if (newFile) {
        let link = this.app.fileManager.generateMarkdownLink(newFile, sourcePath, "", title);
        link = link.trim();
        editor.focus();
        editor.replaceRange(link, context.start, context.end);
        editor.setCursor({
          line: context.start.line,
          ch: context.start.ch + link.length
        });
        this.app.workspace.openLinkText(newFile.path, "", true);
        new import_obsidian4.Notice(`Created new note: "${newFile.basename}"`);
      } else {
        new import_obsidian4.Notice("Error: Failed to create the file.", 5e3);
      }
    } catch (e) {
      console.error("Obsidian Objects: Error in creation flow:", e);
      new import_obsidian4.Notice("Error creating note. See console for details.");
    }
  }
};

// src/main.ts
var ObsidianObjectsPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    console.log("Obsidian Objects: Loading...");
    await this.loadSettings();
    this.templater = new TemplaterHandler(this.app);
    this.addSettingTab(new SettingsTab(this.app, this));
    this.registerEditorSuggest(new TriggerSuggest(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (!this.templater.getApi()) {
        const message = 'Obsidian Objects: The "Templater" plugin is not active. Please install and enable it.';
        new import_obsidian5.Notice(message, 1e4);
        console.warn(message);
      } else {
        console.log("Obsidian Objects: Templater plugin found and ready.");
      }
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
