/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObjectsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  templateFolder: "Templates",
  triggerSymbol: "@",
  triggerTemplates: [
    { trigger: "@project", templateName: "project", outputPath: "Projects/", enabled: true, type: "template" },
    { trigger: "@atomic", templateName: "atomic", outputPath: "Zettelkasten/", enabled: true, type: "template" },
    { trigger: "@person", templateName: "person", enabled: true, type: "template" }
  ],
  defaultOutputPath: "",
  openNewNote: true,
  useProperties: false,
  archiveTag: "",
  archivePropertyKey: "",
  archivePropertyValue: ""
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
var import_obsidian = require("obsidian");
function sanitizeFolderPath(path) {
  if (!path || path.trim() === "")
    return "";
  let sanitized = (0, import_obsidian.normalizePath)(path.trim());
  sanitized = sanitized.replace(/^\/+|\/+$/g, "");
  return sanitized;
}
function sanitizeFileName(name) {
  return name.replace(/[\\/:"*?<>|]/g, "_").trim();
}

// src/settings.ts
var SettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.debouncedSave = (0, import_obsidian2.debounce)(() => {
      void this.plugin.saveSettings();
    }, 500, true);
  }
  /**
   * Renders the entire settings page.
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.renderStatus(containerEl);
    this.renderGeneralConfig(containerEl);
    this.renderArchiveConfig(containerEl);
    this.renderTriggerMappings(containerEl);
    this.renderFooter(containerEl);
  }
  /**
   * Displays the status of integrations (e.g., Templater).
   */
  renderStatus(containerEl) {
    const isTemplaterActive = !!this.plugin.templater.getApi();
    new import_obsidian2.Setting(containerEl).setName("Integration status").setDesc(isTemplaterActive ? "Templater integration is active. Templater syntax (<% ... %>) is processed via the Templater API for every note Objects creates." : "Templater plugin was not detected").then((s) => {
      const statusText = isTemplaterActive ? "Integration active" : "Integration missing";
      const status = s.controlEl.createSpan({
        cls: "objects-status-indicator",
        text: statusText
      });
      status.addClass(isTemplaterActive ? "objects-status-active" : "objects-status-missing");
      if (isTemplaterActive) {
        status.setCssProps({ "--status-color": "var(--color-green)" });
      } else {
        status.setCssProps({ "--status-color": "var(--color-red)" });
      }
    });
  }
  /**
   * Renders configuration like template and output folders.
   */
  renderGeneralConfig(containerEl) {
    new import_obsidian2.Setting(containerEl).setName("Core behavior").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Trigger symbol").setDesc("Character that triggers the template suggester (e.g. @ or #)").addText((text) => text.setPlaceholder("@").setValue(this.plugin.settings.triggerSymbol).onChange(async (v) => {
      const oldSymbol = this.plugin.settings.triggerSymbol;
      const newSymbol = v.trim() || "@";
      if (oldSymbol !== newSymbol) {
        this.plugin.settings.triggerSymbol = newSymbol;
        this.plugin.settings.triggerTemplates.forEach((t) => {
          if (t.trigger.startsWith(oldSymbol)) {
            t.trigger = newSymbol + t.trigger.substring(oldSymbol.length);
          } else if (!t.trigger.startsWith(newSymbol)) {
            t.trigger = newSymbol + t.trigger;
          }
        });
        await this.plugin.saveSettings();
        this.display();
      }
    }));
    new import_obsidian2.Setting(containerEl).setName("Template folder").setDesc("Root directory for your Markdown templates").addText((text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templateFolder).onChange((v) => {
      this.plugin.settings.templateFolder = sanitizeFolderPath(v);
      this.debouncedSave();
    }));
    new import_obsidian2.Setting(containerEl).setName("Default output path").setDesc("Fallback folder for newly created notes, if not defined in the mapping").addText((text) => text.setPlaceholder("Inbox").setValue(this.plugin.settings.defaultOutputPath).onChange((v) => {
      this.plugin.settings.defaultOutputPath = sanitizeFolderPath(v);
      this.debouncedSave();
    }));
    new import_obsidian2.Setting(containerEl).setName("Use file properties").setDesc("Whether to allow defining and filtering by frontmatter properties").addToggle((toggle) => toggle.setValue(this.plugin.settings.useProperties).onChange(async (v) => {
      this.plugin.settings.useProperties = v;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian2.Setting(containerEl).setName("Open created note").setDesc("Whether to automatically open the newly created note in a new tab").addToggle((toggle) => toggle.setValue(this.plugin.settings.openNewNote).onChange((v) => {
      this.plugin.settings.openNewNote = v;
      this.debouncedSave();
    }));
  }
  /**
   * Renders archive settings.
   */
  renderArchiveConfig(containerEl) {
    new import_obsidian2.Setting(containerEl).setName("Archive behavior").setDesc("Define how to identify archived notes to exclude them from suggestions").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Archive tag").setDesc("Tag that marks a note as archived (e.g. #archived)").addText((text) => text.setPlaceholder("#archived").setValue(this.plugin.settings.archiveTag).onChange((v) => {
      this.plugin.settings.archiveTag = v.trim();
      this.debouncedSave();
    }));
    new import_obsidian2.Setting(containerEl).setName("Archive property key").setDesc("Frontmatter property key to identify archived notes (e.g. Archived)").addText((text) => text.setPlaceholder("Archived").setValue(this.plugin.settings.archivePropertyKey).onChange((v) => {
      this.plugin.settings.archivePropertyKey = v.trim();
      this.debouncedSave();
    }));
    new import_obsidian2.Setting(containerEl).setName("Archive property value").setDesc("Expected value for the archive property").addText((text) => text.setPlaceholder("True").setValue(this.plugin.settings.archivePropertyValue).onChange((v) => {
      this.plugin.settings.archivePropertyValue = v.trim();
      this.debouncedSave();
    }));
  }
  /**
   * Renders the list of trigger mappings.
   */
  renderTriggerMappings(containerEl) {
    new import_obsidian2.Setting(containerEl).setName("Trigger mappings").setHeading();
    this.plugin.settings.triggerTemplates.forEach((mapping, index) => {
      this.renderMappingRow(containerEl, mapping, index);
    });
    new import_obsidian2.Setting(containerEl).addButton((btn) => btn.setButtonText("Add new mapping").setCta().onClick(async () => {
      const symbol = this.plugin.settings.triggerSymbol;
      this.plugin.settings.triggerTemplates.push({ trigger: symbol, templateName: "", enabled: true, type: "template" });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
  /**
   * Renders a single mapping row using a polished Card/Accordion layout.
   */
  renderMappingRow(containerEl, mapping, index) {
    const symbol = this.plugin.settings.triggerSymbol;
    const useProperties = this.plugin.settings.useProperties;
    const detailsEl = containerEl.createEl("details");
    detailsEl.addClass("objects-mapping-details");
    if (!mapping.trigger || mapping.trigger === symbol) {
      detailsEl.setAttribute("open", "");
    }
    const summaryEl = detailsEl.createEl("summary");
    summaryEl.addClass("objects-mapping-summary");
    const titleText = mapping.trigger && mapping.trigger !== symbol ? `Mapping: ${mapping.trigger}` : `New Mapping (#${index + 1})`;
    const headerSetting = new import_obsidian2.Setting(summaryEl).setName(titleText);
    headerSetting.settingEl.addClass("objects-mapping-header");
    headerSetting.addToggle((t) => t.setValue(mapping.enabled).setTooltip(mapping.enabled ? "Disable mapping" : "Enable mapping").onChange(async (v) => {
      mapping.enabled = v;
      t.setTooltip(v ? "Disable mapping" : "Enable mapping");
      await this.plugin.saveSettings();
    }));
    headerSetting.addExtraButton((b) => b.setIcon("trash").setTooltip("Delete mapping").onClick(async () => {
      this.plugin.settings.triggerTemplates.splice(index, 1);
      await this.plugin.saveSettings();
      this.display();
    }));
    headerSetting.controlEl.addEventListener("click", (e) => {
      e.stopPropagation();
    });
    const contentEl = detailsEl.createDiv();
    contentEl.addClass("objects-mapping-content");
    new import_obsidian2.Setting(contentEl).setName("Type").setDesc("Select whether this trigger inserts a template or executes a command.").addDropdown((dropdown) => dropdown.addOption("template", "Template").addOption("command", "Obsidian command").setValue(mapping.type || "template").onChange((value) => {
      mapping.type = value;
      this.display();
    }));
    new import_obsidian2.Setting(contentEl).setName("Trigger text").setDesc("The text that initiates this action.").addText((t) => t.setPlaceholder(symbol + "trigger").setValue(mapping.trigger).onChange((v) => {
      mapping.trigger = v.startsWith(symbol) ? v : v ? symbol + v : symbol;
      t.setValue(mapping.trigger);
      headerSetting.setName(`Mapping: ${mapping.trigger}`);
      this.debouncedSave();
    }));
    if (mapping.type === "command") {
      new import_obsidian2.Setting(contentEl).setName("Command").setDesc("The Obsidian command to execute.").addText((t) => {
        new CommandSuggest(this.app, t.inputEl);
        t.setPlaceholder("Search command...").setValue(mapping.commandName || "").onChange(() => {
          this.debouncedSave();
        });
        t.inputEl.addEventListener("command-selected", (e) => {
          mapping.commandId = e.detail.id;
          mapping.commandName = e.detail.name;
          t.setValue(mapping.commandName || "");
          this.debouncedSave();
        });
      });
    } else {
      new import_obsidian2.Setting(contentEl).setName("Template file").setDesc("The template to be inserted.").addText((t) => {
        new TemplateSuggest(this.app, t.inputEl, this.plugin);
        t.setPlaceholder("Template").setValue(mapping.templateName || "").onChange((v) => {
          mapping.templateName = v ? v.replace(/\.md$/, "") : "";
          this.debouncedSave();
        });
      });
      new import_obsidian2.Setting(contentEl).setName("Target folder").setDesc("Where the generated file should be saved.").addText((t) => {
        new FolderSuggest(this.app, t.inputEl);
        t.setPlaceholder("Target folder").setValue(mapping.outputPath || "").onChange((v) => {
          mapping.outputPath = sanitizeFolderPath(v);
          this.debouncedSave();
        });
      });
      if (useProperties) {
        new import_obsidian2.Setting(contentEl).setName("Property key").setDesc("Frontmatter property key.").addText((t) => t.setPlaceholder("Key").setValue(mapping.propertyKey || "").onChange((v) => {
          mapping.propertyKey = v;
          this.debouncedSave();
        }));
        new import_obsidian2.Setting(contentEl).setName("Property value").setDesc("Frontmatter property value.").addText((t) => t.setPlaceholder("Value").setValue(mapping.propertyValue || "").onChange((v) => {
          mapping.propertyValue = v;
          this.debouncedSave();
        }));
      }
    }
  }
  renderFooter(containerEl) {
    const symbol = this.plugin.settings.triggerSymbol;
    containerEl.createDiv({
      cls: "objects-settings-footer",
      text: `Settings are saved automatically. Triggers must start with ${symbol}.`
    });
  }
};
var TemplateSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl, plugin) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.plugin = plugin;
  }
  getSuggestions(query) {
    const root = sanitizeFolderPath(this.plugin.settings.templateFolder);
    if (!root)
      return [];
    const lower = query.toLowerCase();
    return this.app.vault.getMarkdownFiles().filter(
      (f) => {
        var _a;
        return (f.path.startsWith(root + "/") || ((_a = f.parent) == null ? void 0 : _a.path) === root) && f.path.toLowerCase().includes(lower);
      }
    );
  }
  renderSuggestion(file, el) {
    const root = sanitizeFolderPath(this.plugin.settings.templateFolder);
    const rel = file.path.startsWith(root + "/") ? file.path.substring(root.length + 1) : file.path;
    el.setText(rel.replace(/\.md$/, ""));
  }
  selectSuggestion(file) {
    const root = sanitizeFolderPath(this.plugin.settings.templateFolder);
    const rel = file.path.startsWith(root + "/") ? file.path.substring(root.length + 1) : file.path;
    this.inputEl.value = rel.replace(/\.md$/, "");
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};
var FolderSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const lowerCaseInput = query.toLowerCase();
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian2.TFolder).map((f) => f.path);
    return folders.filter(
      (folderPath) => folderPath.toLowerCase().includes(lowerCaseInput)
    );
  }
  renderSuggestion(folder, el) {
    el.setText(folder === "/" ? "Vault Root (/)" : folder);
  }
  selectSuggestion(folder) {
    this.inputEl.value = folder;
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};
var CommandSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const appWithCommands = this.app;
    const commands = appWithCommands.commands.listCommands();
    const lowerQuery = query.toLowerCase();
    return commands.filter((cmd) => cmd.name.toLowerCase().includes(lowerQuery));
  }
  renderSuggestion(cmd, el) {
    el.setText(cmd.name);
  }
  selectSuggestion(cmd) {
    this.inputEl.value = cmd.name;
    this.inputEl.dispatchEvent(new CustomEvent("command-selected", { detail: cmd }));
    this.close();
  }
};

// src/templater.ts
var import_obsidian3 = require("obsidian");
var TemplaterHandler = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Tries to get the Templater API if the plugin is enabled.
   * @returns The Templater API or null if the plugin is not active.
   */
  getApi() {
    const plugins = this.app.plugins;
    if (!plugins || !plugins.enabledPlugins.has("templater-obsidian")) {
      return null;
    }
    const plugin = plugins.plugins["templater-obsidian"];
    return (plugin == null ? void 0 : plugin.templater) || null;
  }
  /**
   * Creates a new note from a template.
   *
   * When Templater is available and a template is provided, delegates to its
   * create_new_note_from_template API. This guarantees that <% %> tags are
   * processed regardless of the user's "Trigger Templater on new file creation"
   * setting. Otherwise falls back to manual creation with the basic
   * {{title}} / {{date}} / {{time}} placeholders.
   */
  async createNoteFromTemplate(templateFile, folderPath, fileName, propertyKey, propertyValue) {
    const api = this.getApi();
    const sanitizedFolder = sanitizeFolderPath(folderPath);
    let newFile = null;
    if (api && templateFile) {
      try {
        newFile = await api.create_new_note_from_template(
          templateFile,
          sanitizedFolder,
          fileName,
          false
        );
      } catch (e) {
        console.warn("Objects: Templater API failed, falling back to manual creation:", e);
        newFile = null;
      }
    }
    if (!newFile) {
      const newNotePath = (0, import_obsidian3.normalizePath)(sanitizedFolder ? `${sanitizedFolder}/${fileName}.md` : `${fileName}.md`);
      let content = "";
      if (templateFile) {
        content = await this.app.vault.read(templateFile);
      }
      content = this.replacePlaceholders(content, fileName);
      try {
        newFile = await this.app.vault.create(newNotePath, content);
      } catch (error) {
        console.warn(`Objects: Failed to create file at "${newNotePath}":`, error);
        return null;
      }
    }
    if (newFile && propertyKey && propertyValue) {
      try {
        await this.app.fileManager.processFrontMatter(newFile, (frontmatter) => {
          frontmatter[propertyKey] = propertyValue;
        });
      } catch (e) {
        console.warn("Objects: Failed to add frontmatter properties:", e);
      }
    }
    return newFile;
  }
  /**
   * Basic placeholder replacement for the fallback system.
   * Supports {{title}}, {{date}} (YYYY-MM-DD), and {{time}} (HH:mm).
   */
  replacePlaceholders(content, title) {
    const now = (0, import_obsidian3.moment)();
    const replacements = {
      "{{title}}": title,
      "{{date}}": now.format("YYYY-MM-DD"),
      "{{time}}": now.format("HH:mm")
    };
    let result = content;
    for (const [placeholder, value] of Object.entries(replacements)) {
      result = result.split(placeholder).join(value);
    }
    return result;
  }
};

// src/suggester.ts
var import_obsidian5 = require("obsidian");

// src/modal.ts
var import_obsidian4 = require("obsidian");
var TitleModal = class extends import_obsidian4.Modal {
  /**
   * @param app Obsidian App instance
   * @param plugin Reference to the main plugin
   * @param mapping The trigger mapping being used
   * @param onSubmit Callback function on successful input (returns title and openNote flag)
   */
  constructor(app, plugin, mapping, onSubmit) {
    super(app);
    this.result = "";
    this.openNote = true;
    this.isClosed = false;
    this.plugin = plugin;
    this.mapping = mapping;
    this.onSubmit = onSubmit;
    this.openNote = plugin.settings.openNewNote;
  }
  /**
   * Creates the modal UI.
   */
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText("Create or link note");
    contentEl.createDiv({ text: "Enter note title:", cls: "objects-modal-description" });
    const inputContainer = contentEl.createDiv({ cls: "objects-modal-input-container" });
    const textComponent = new import_obsidian4.TextComponent(inputContainer);
    const inputEl = textComponent.inputEl;
    inputEl.addClass("objects-modal-input");
    inputEl.placeholder = "My new note";
    inputEl.value = this.result;
    textComponent.onChange((value) => {
      this.result = value;
    });
    new FileSuggest(this.app, inputEl, this.plugin, this.mapping);
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        activeWindow.setTimeout(() => this.submit(), 100);
      }
    });
    activeWindow.setTimeout(() => {
      if (!this.isClosed) {
        inputEl.focus();
      }
    }, 50);
    new import_obsidian4.Setting(contentEl).setName("Open note after creation").addToggle(
      (toggle) => toggle.setValue(this.openNote).onChange((value) => {
        this.openNote = value;
      })
    );
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const submitBtn = buttonContainer.createEl("button", {
      text: "Create or link",
      cls: "mod-cta"
    });
    submitBtn.addEventListener("click", () => this.submit());
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.addEventListener("click", () => this.close());
  }
  /**
   * Validates input and executes the submit callback.
   */
  submit() {
    if (this.isClosed)
      return;
    const trimmed = this.result.trim();
    if (trimmed.length > 0) {
      this.onSubmit(trimmed, this.openNote);
      this.close();
    }
  }
  /**
   * Cleans up the modal on close.
   */
  onClose() {
    this.isClosed = true;
    this.contentEl.empty();
  }
};
var FileSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor(app, inputEl, plugin, mapping) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.plugin = plugin;
    this.mapping = mapping;
  }
  /**
   * Filters all markdown files based on the target folder and query.
   */
  getSuggestions(query) {
    const lowerCaseQuery = query.toLowerCase();
    const files = this.app.vault.getMarkdownFiles();
    const folder = this.mapping.outputPath || this.plugin.settings.defaultOutputPath;
    const normalizedTarget = sanitizeFolderPath(folder);
    const { propertyKey, propertyValue } = this.mapping;
    const { useProperties, archiveTag, archivePropertyKey, archivePropertyValue } = this.plugin.settings;
    const normalizedArchiveTag = archiveTag ? archiveTag.replace(/^#/, "").toLowerCase() : null;
    return files.filter((file) => {
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache) {
        if (normalizedArchiveTag) {
          const tags = (0, import_obsidian4.getAllTags)(cache);
          if (tags && tags.some((tag) => tag.replace(/^#/, "").toLowerCase() === normalizedArchiveTag)) {
            return false;
          }
        }
        if (archivePropertyKey && archivePropertyValue) {
          const frontmatter = cache.frontmatter;
          if (frontmatter) {
            const val = frontmatter[archivePropertyKey];
            if (val !== void 0 && (typeof val === "string" || typeof val === "number" || typeof val === "boolean") && String(val).toLowerCase() === archivePropertyValue.toLowerCase()) {
              return false;
            }
          }
        }
      }
      if (normalizedTarget !== "") {
        const folderPath = file.parent ? sanitizeFolderPath(file.parent.path) : "";
        if (folderPath !== normalizedTarget)
          return false;
      }
      if (useProperties && propertyKey && propertyValue) {
        const frontmatter = cache == null ? void 0 : cache.frontmatter;
        if (!frontmatter)
          return false;
        const val = frontmatter[propertyKey];
        if (val !== void 0 && (typeof val === "string" || typeof val === "number" || typeof val === "boolean") && String(val).toLowerCase() !== propertyValue.toLowerCase()) {
          return false;
        }
      }
      const matchesQuery = file.basename.toLowerCase().includes(lowerCaseQuery);
      return matchesQuery;
    }).slice(0, 10);
  }
  renderSuggestion(file, el) {
    el.setText(file.basename);
  }
  selectSuggestion(file) {
    this.inputEl.value = file.basename;
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};

// src/suggester.ts
var TriggerSuggest = class extends import_obsidian5.EditorSuggest {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  /**
   * Checks if the suggester should be triggered at the current cursor position.
   * Trigger: '@' at the start of a line or after a space.
   */
  onTrigger(cursor, editor) {
    const line = editor.getLine(cursor.line).substring(0, cursor.ch);
    const symbol = this.plugin.settings.triggerSymbol;
    const escapedSymbol = symbol.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(`${escapedSymbol}([^\\s]*)$`);
    const match = regex.exec(line);
    if (!match)
      return null;
    const query = match[1];
    const triggerStart = line.length - match[0].length;
    if (triggerStart > 0) {
      const charBefore = line.charAt(triggerStart - 1);
      if (/\w/.test(charBefore)) {
        return null;
      }
    }
    return {
      start: { line: cursor.line, ch: triggerStart },
      end: cursor,
      query
    };
  }
  /**
   * Provides matching mapping suggestions based on previous input.
   */
  getSuggestions(context) {
    const query = context.query.toLowerCase();
    const symbol = this.plugin.settings.triggerSymbol;
    return this.plugin.settings.triggerTemplates.filter(
      (t) => t.enabled && t.trigger.toLowerCase().startsWith(symbol + query)
    );
  }
  renderSuggestion(suggestion, el) {
    el.setText(suggestion.trigger);
  }
  /**
   * Called when a suggestion is selected.
   * Opens the modal for title entry or executes a command.
   */
  selectSuggestion(suggestion) {
    const context = this.context;
    if (!context)
      return;
    if (suggestion.type === "command" && suggestion.commandId) {
      context.editor.replaceRange("", context.start, context.end);
      const appWithCommands = this.app;
      const success = appWithCommands.commands.executeCommandById(suggestion.commandId);
      if (!success) {
        new import_obsidian5.Notice(`Command "${suggestion.commandName || suggestion.commandId}" could not be executed.`);
      }
      context.editor.focus();
      return;
    }
    new TitleModal(this.app, this.plugin, suggestion, (title, openNote) => {
      void this.handleNoteCreation(suggestion, title, openNote, context);
    }).open();
  }
  /**
   * Central logic for creating a new note or linking to an existing one.
   */
  async handleNoteCreation(suggestion, title, openNote, context) {
    var _a;
    const editor = context.editor;
    const sanitizedTitle = sanitizeFileName(title);
    const sourcePath = ((_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) || "";
    const existingFile = this.findExistingFile(sanitizedTitle, suggestion);
    if (existingFile) {
      this.insertLinkAndFocus(editor, existingFile, sourcePath, title, context);
      new import_obsidian5.Notice(`Linked to existing note: "${existingFile.basename}"`);
      return;
    }
    const templateFile = this.getTemplateFile(suggestion);
    if (!templateFile && suggestion.templateName) {
      new import_obsidian5.Notice(`Template "${suggestion.templateName}" not found. Creating note without template.`, 3e3);
    }
    try {
      const folder = suggestion.outputPath || this.plugin.settings.defaultOutputPath;
      const targetFolder = sanitizeFolderPath(folder);
      if (targetFolder && !this.app.vault.getAbstractFileByPath(targetFolder)) {
        await this.app.vault.createFolder(targetFolder);
      }
      const useProperties = this.plugin.settings.useProperties;
      const newFile = await this.plugin.templater.createNoteFromTemplate(
        templateFile,
        targetFolder,
        sanitizedTitle,
        useProperties ? suggestion.propertyKey : void 0,
        useProperties ? suggestion.propertyValue : void 0
      );
      if (newFile) {
        this.insertLinkAndFocus(editor, newFile, sourcePath, title, context);
        if (openNote) {
          await this.app.workspace.openLinkText(newFile.path, "", true);
        }
        new import_obsidian5.Notice(`Created new note: "${newFile.basename}"`);
      } else {
        new import_obsidian5.Notice("Error: failed to create file.", 5e3);
      }
    } catch (e) {
      console.warn("Objects: Error in creation process:", e);
      new import_obsidian5.Notice("Error creating note. See console for details.");
    }
  }
  /**
   * Looks for a file. First exactly in the target path; only falls back to a vault-wide
   * lookup when no target folder is configured. With a target folder set, a vault-wide
   * fallback could match a homonymous note in an unrelated folder and link to the wrong one.
   */
  findExistingFile(title, suggestion) {
    const folder = suggestion.outputPath || this.plugin.settings.defaultOutputPath;
    const targetFolder = sanitizeFolderPath(folder);
    const specificPath = (0, import_obsidian5.normalizePath)(targetFolder ? `${targetFolder}/${title}.md` : `${title}.md`);
    const fileAtTable = this.app.vault.getAbstractFileByPath(specificPath);
    if (fileAtTable instanceof import_obsidian5.TFile)
      return fileAtTable;
    if (!targetFolder) {
      return this.app.metadataCache.getFirstLinkpathDest(title, "");
    }
    return null;
  }
  /**
   * Tries to load the configured template as a TFile.
   */
  getTemplateFile(suggestion) {
    var _a;
    const templateName = (_a = suggestion.templateName) == null ? void 0 : _a.trim();
    if (!templateName)
      return null;
    const templateFolder = sanitizeFolderPath(this.plugin.settings.templateFolder);
    const templatePath = (0, import_obsidian5.normalizePath)(templateFolder ? `${templateFolder}/${templateName}.md` : `${templateName}.md`);
    const file = this.app.vault.getAbstractFileByPath(templatePath);
    return file instanceof import_obsidian5.TFile ? file : null;
  }
  /**
   * Inserts the markdown link into the editor and sets the focus.
   */
  insertLinkAndFocus(editor, file, sourcePath, alias, context) {
    const link = this.app.fileManager.generateMarkdownLink(file, sourcePath, "", alias).trim();
    editor.replaceRange(link, context.start, context.end);
    const newCursorPos = {
      line: context.start.line,
      ch: context.start.ch + link.length
    };
    editor.setCursor(newCursorPos);
    editor.focus();
  }
};

// src/main.ts
var ObjectsPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    /** Current configuration of the plugin */
    this.settings = DEFAULT_SETTINGS;
  }
  /**
   * Initializes the plugin when loaded into Obsidian.
   */
  async onload() {
    console.debug("Objects: Loading...");
    await this.loadSettings();
    this.templater = new TemplaterHandler(this.app);
    this.addSettingTab(new SettingsTab(this.app, this));
    this.registerEditorSuggest(new TriggerSuggest(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.verifyIntegrations();
    });
  }
  /**
   * Checks if necessary third-party plugins (like Templater) are active.
   */
  verifyIntegrations() {
    const api = this.templater.getApi();
  }
  /**
   * Loads saved settings and merges them with default values.
   */
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
    if (this.settings.triggerTemplates) {
      this.settings.triggerTemplates.forEach((mapping) => {
        if (mapping.enabled === void 0) {
          mapping.enabled = true;
        }
        if (mapping.type === void 0) {
          mapping.type = "template";
        }
      });
    }
  }
  /**
   * Permanently saves current settings.
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
