/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObjectsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  templateFolder: "Templates",
  triggerTemplates: [
    { trigger: "@project", templateName: "project", outputPath: "Projects/", enabled: true },
    { trigger: "@atomic", templateName: "atomic", outputPath: "Zettelkasten/", enabled: true },
    { trigger: "@person", templateName: "person", enabled: true }
  ],
  defaultOutputPath: ""
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
var import_obsidian = require("obsidian");
function sanitizeFolderPath(path) {
  if (!path || path.trim() === "")
    return "";
  let sanitized = (0, import_obsidian.normalizePath)(path.trim());
  sanitized = sanitized.replace(/^\/+|\/+$/g, "");
  return sanitized;
}
function sanitizeFileName(name) {
  return name.replace(/[\\/:"*?<>|]/g, "_").trim();
}

// src/settings.ts
var SettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.debouncedSave = (0, import_obsidian2.debounce)(() => this.plugin.saveSettings(), 500, true);
  }
  /**
   * Renders the entire settings page.
   */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.renderStatus(containerEl);
    this.renderGeneralConfig(containerEl);
    this.renderTriggerMappings(containerEl);
    this.renderFooter(containerEl);
  }
  /**
   * Displays the status of integrations (e.g., Templater).
   */
  renderStatus(containerEl) {
    const isTemplaterActive = !!this.plugin.templater.getApi();
    new import_obsidian2.Setting(containerEl).setName("Integrations status").setDesc(isTemplaterActive ? "Templater integration is active." : "Templater plugin was not detected.").then((s) => {
      const status = s.controlEl.createSpan({
        cls: "objects-status-indicator",
        text: isTemplaterActive ? "\u2714 Active" : "\u2718 Missing"
      });
      status.addClass(isTemplaterActive ? "objects-status-active" : "objects-status-missing");
    });
  }
  /**
   * Renders general configuration like template and output folders.
   */
  renderGeneralConfig(containerEl) {
    new import_obsidian2.Setting(containerEl).setName("General configuration").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Template folder").setDesc("Root directory for your markdown templates.").addText((text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templateFolder).onChange((v) => {
      this.plugin.settings.templateFolder = sanitizeFolderPath(v);
      this.debouncedSave();
    }));
    new import_obsidian2.Setting(containerEl).setName("Default output path").setDesc("Fallback folder for newly created notes, if not defined in the mapping.").addText((text) => text.setPlaceholder("Inbox").setValue(this.plugin.settings.defaultOutputPath).onChange((v) => {
      this.plugin.settings.defaultOutputPath = sanitizeFolderPath(v);
      this.debouncedSave();
    }));
  }
  /**
   * Renders the list of trigger mappings.
   */
  renderTriggerMappings(containerEl) {
    new import_obsidian2.Setting(containerEl).setName("Trigger mappings").setHeading();
    this.plugin.settings.triggerTemplates.forEach((mapping, index) => {
      this.renderMappingRow(containerEl, mapping, index);
    });
    new import_obsidian2.Setting(containerEl).addButton((btn) => btn.setButtonText("Add new mapping").setCta().onClick(async () => {
      this.plugin.settings.triggerTemplates.push({ trigger: "@", templateName: "", enabled: true });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
  /**
   * Renders a single mapping row (Trigger, Template, Path, Status).
   */
  renderMappingRow(containerEl, mapping, index) {
    const s = new import_obsidian2.Setting(containerEl).addToggle((t) => t.setValue(mapping.enabled).onChange(async (v) => {
      mapping.enabled = v;
      await this.plugin.saveSettings();
    })).addText((t) => t.setPlaceholder("@trigger").setValue(mapping.trigger).onChange((v) => {
      mapping.trigger = v.startsWith("@") ? v : v ? "@" + v : "@";
      t.setValue(mapping.trigger);
      this.debouncedSave();
    })).addText((t) => {
      new TemplateSuggest(this.app, t.inputEl, this.plugin);
      t.setPlaceholder("Template").setValue(mapping.templateName).onChange((v) => {
        mapping.templateName = v.replace(/\.md$/, "");
        this.debouncedSave();
      });
    }).addText((t) => t.setPlaceholder("Target folder").setValue(mapping.outputPath || "").onChange((v) => {
      mapping.outputPath = sanitizeFolderPath(v);
      this.debouncedSave();
    })).addExtraButton((b) => b.setIcon("trash").setTooltip("Delete mapping").onClick(async () => {
      this.plugin.settings.triggerTemplates.splice(index, 1);
      await this.plugin.saveSettings();
      this.display();
    }));
    s.infoEl.remove();
    s.controlEl.addClass("objects-mapping-control");
  }
  renderFooter(containerEl) {
    containerEl.createDiv({
      cls: "objects-settings-footer",
      text: "Settings are saved automatically. Triggers must start with @."
    });
  }
};
var TemplateSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, inputEl, plugin) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.plugin = plugin;
  }
  getSuggestions(query) {
    const root = sanitizeFolderPath(this.plugin.settings.templateFolder);
    if (!root)
      return [];
    const lower = query.toLowerCase();
    return this.app.vault.getMarkdownFiles().filter(
      (f) => {
        var _a;
        return (f.path.startsWith(root + "/") || ((_a = f.parent) == null ? void 0 : _a.path) === root) && f.path.toLowerCase().includes(lower);
      }
    );
  }
  renderSuggestion(file, el) {
    const root = sanitizeFolderPath(this.plugin.settings.templateFolder);
    const rel = file.path.startsWith(root + "/") ? file.path.substring(root.length + 1) : file.path;
    el.setText(rel.replace(/\.md$/, ""));
  }
  selectSuggestion(file) {
    const root = sanitizeFolderPath(this.plugin.settings.templateFolder);
    const rel = file.path.startsWith(root + "/") ? file.path.substring(root.length + 1) : file.path;
    this.inputEl.value = rel.replace(/\.md$/, "");
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};

// src/templater.ts
var import_obsidian3 = require("obsidian");
var TemplaterHandler = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Tries to get the Templater API if the plugin is enabled.
   * @returns The Templater API or null if the plugin is not active.
   */
  getApi() {
    const plugins = this.app.plugins;
    if (!plugins || !plugins.enabledPlugins.has("templater-obsidian")) {
      return null;
    }
    const plugin = plugins.plugins["templater-obsidian"];
    return (plugin == null ? void 0 : plugin.templater) || null;
  }
  /**
   * Creates a new note from a template.
   */
  async createNoteFromTemplate(templateFile, folderPath, fileName) {
    const api = this.getApi();
    const sanitizedFolder = sanitizeFolderPath(folderPath);
    const newNotePath = (0, import_obsidian3.normalizePath)(sanitizedFolder ? `${sanitizedFolder}/${fileName}.md` : `${fileName}.md`);
    if (api && templateFile) {
      return await api.create_new_note_from_template(templateFile, sanitizedFolder, fileName, false);
    }
    let content = "";
    if (templateFile) {
      content = await this.app.vault.read(templateFile);
      content = this.replacePlaceholders(content, fileName);
    }
    try {
      return await this.app.vault.create(newNotePath, content);
    } catch (error) {
      console.error(`Objects: Failed to create file at "${newNotePath}":`, error);
      return null;
    }
  }
  /**
   * Basic placeholder replacement for the fallback system.
   * Supports {{title}}, {{date}} (YYYY-MM-DD), and {{time}} (HH:mm).
   */
  replacePlaceholders(content, title) {
    const now = (0, import_obsidian3.moment)();
    const replacements = {
      "{{title}}": title,
      "{{date}}": now.format("YYYY-MM-DD"),
      "{{time}}": now.format("HH:mm")
    };
    let result = content;
    for (const [placeholder, value] of Object.entries(replacements)) {
      result = result.split(placeholder).join(value);
    }
    return result;
  }
};

// src/suggester.ts
var import_obsidian5 = require("obsidian");

// src/modal.ts
var import_obsidian4 = require("obsidian");
var TitleModal = class extends import_obsidian4.Modal {
  /**
   * @param app Obsidian App instance
   * @param plugin Reference to the main plugin
   * @param targetFolder Target folder for file search/creation
   * @param onSubmit Callback function on successful input
   */
  constructor(app, plugin, targetFolder, onSubmit) {
    super(app);
    this.result = "";
    this.isClosed = false;
    this.plugin = plugin;
    this.targetFolder = targetFolder;
    this.onSubmit = onSubmit;
  }
  /**
   * Creates the modal UI.
   */
  onOpen() {
    const { contentEl } = this;
    new import_obsidian4.Setting(contentEl).setName("Enter note title").setHeading();
    const inputSetting = new import_obsidian4.Setting(contentEl).setName("Title").addText((text) => {
      text.setPlaceholder("My new note").setValue(this.result).onChange((value) => {
        this.result = value;
      });
      new FileSuggest(this.app, text.inputEl, this.plugin, this.targetFolder);
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          setTimeout(() => this.submit(), 100);
        }
      });
      text.inputEl.focus();
    });
    inputSetting.infoEl.remove();
    new import_obsidian4.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create or Link").setCta().onClick(() => this.submit())
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => this.close())
    );
  }
  /**
   * Validates input and executes the submit callback.
   */
  submit() {
    if (this.isClosed)
      return;
    const trimmed = this.result.trim();
    if (trimmed.length > 0) {
      this.onSubmit(trimmed);
      this.close();
    }
  }
  /**
   * Cleans up the modal on close.
   */
  onClose() {
    this.isClosed = true;
    this.contentEl.empty();
  }
};
var FileSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor(app, inputEl, plugin, targetFolder) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.plugin = plugin;
    this.targetFolder = targetFolder;
  }
  /**
   * Filters all markdown files based on the target folder and query.
   */
  getSuggestions(query) {
    const lowerCaseQuery = query.toLowerCase();
    const files = this.app.vault.getMarkdownFiles();
    const normalizedTarget = sanitizeFolderPath(this.targetFolder);
    return files.filter((file) => {
      const folderPath = file.parent ? sanitizeFolderPath(file.parent.path) : "";
      const isInFolder = normalizedTarget === "" || folderPath === normalizedTarget;
      const matchesQuery = file.basename.toLowerCase().includes(lowerCaseQuery);
      return isInFolder && matchesQuery;
    }).slice(0, 10);
  }
  renderSuggestion(file, el) {
    el.setText(file.basename);
  }
  selectSuggestion(file) {
    this.inputEl.value = file.basename;
    this.inputEl.dispatchEvent(new Event("input"));
    this.close();
  }
};

// src/suggester.ts
var TriggerSuggest = class extends import_obsidian5.EditorSuggest {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  /**
   * Checks if the suggester should be triggered at the current cursor position.
   * Trigger: '@' at the start of a line or after a space.
   */
  onTrigger(cursor, editor) {
    const line = editor.getLine(cursor.line).substring(0, cursor.ch);
    const match = /@(\w*)$/.exec(line);
    if (!match)
      return null;
    const query = match[1];
    const triggerStart = line.lastIndexOf("@");
    if (triggerStart > 0 && line.charAt(triggerStart - 1) !== " ") {
      return null;
    }
    return {
      start: { line: cursor.line, ch: triggerStart },
      end: cursor,
      query
    };
  }
  /**
   * Provides matching mapping suggestions based on previous input.
   */
  getSuggestions(context) {
    const query = context.query.toLowerCase();
    return this.plugin.settings.triggerTemplates.filter(
      (t) => t.enabled && t.trigger.toLowerCase().startsWith("@" + query)
    );
  }
  renderSuggestion(suggestion, el) {
    el.setText(suggestion.trigger);
  }
  /**
   * Called when a suggestion is selected.
   * Opens the modal for title entry.
   */
  async selectSuggestion(suggestion, evt) {
    const context = this.context;
    if (!context)
      return;
    const folder = suggestion.outputPath || this.plugin.settings.defaultOutputPath;
    const targetFolder = sanitizeFolderPath(folder);
    new TitleModal(this.app, this.plugin, targetFolder, async (title) => {
      await this.handleNoteCreation(suggestion, title, context);
    }).open();
  }
  /**
   * Central logic for creating a new note or linking to an existing one.
   */
  async handleNoteCreation(suggestion, title, context) {
    var _a;
    const editor = context.editor;
    const sanitizedTitle = sanitizeFileName(title);
    const sourcePath = ((_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) || "";
    const existingFile = this.findExistingFile(sanitizedTitle, suggestion);
    if (existingFile) {
      this.insertLinkAndFocus(editor, existingFile, sourcePath, title, context);
      new import_obsidian5.Notice(`Linked to existing note: "${existingFile.basename}"`);
      return;
    }
    const templateFile = await this.getTemplateFile(suggestion);
    if (!templateFile && suggestion.templateName) {
      new import_obsidian5.Notice(`Template "${suggestion.templateName}" not found. Creating note without template.`, 3e3);
    }
    try {
      const folder = suggestion.outputPath || this.plugin.settings.defaultOutputPath;
      const targetFolder = sanitizeFolderPath(folder);
      if (targetFolder && !this.app.vault.getAbstractFileByPath(targetFolder)) {
        await this.app.vault.createFolder(targetFolder);
      }
      const newFile = await this.plugin.templater.createNoteFromTemplate(
        templateFile,
        targetFolder,
        sanitizedTitle
      );
      if (newFile) {
        this.insertLinkAndFocus(editor, newFile, sourcePath, title, context);
        this.app.workspace.openLinkText(newFile.path, "", true);
        new import_obsidian5.Notice(`Created new note: "${newFile.basename}"`);
      } else {
        new import_obsidian5.Notice("Error: Failed to create file.", 5e3);
      }
    } catch (e) {
      console.error("Objects: Error in creation process:", e);
      new import_obsidian5.Notice("Error creating note. See console for details.");
    }
  }
  /**
   * Looks for a file. First exactly in the target path, then via MetadataCache in the entire vault.
   */
  findExistingFile(title, suggestion) {
    const folder = suggestion.outputPath || this.plugin.settings.defaultOutputPath;
    const targetFolder = sanitizeFolderPath(folder);
    const specificPath = (0, import_obsidian5.normalizePath)(targetFolder ? `${targetFolder}/${title}.md` : `${title}.md`);
    const fileAtTable = this.app.vault.getAbstractFileByPath(specificPath);
    if (fileAtTable instanceof import_obsidian5.TFile)
      return fileAtTable;
    return this.app.metadataCache.getFirstLinkpathDest(title, "");
  }
  /**
   * Tries to load the configured template as a TFile.
   */
  async getTemplateFile(suggestion) {
    var _a;
    const templateName = (_a = suggestion.templateName) == null ? void 0 : _a.trim();
    if (!templateName)
      return null;
    const templateFolder = sanitizeFolderPath(this.plugin.settings.templateFolder);
    const templatePath = (0, import_obsidian5.normalizePath)(templateFolder ? `${templateFolder}/${templateName}.md` : `${templateName}.md`);
    const file = this.app.vault.getAbstractFileByPath(templatePath);
    return file instanceof import_obsidian5.TFile ? file : null;
  }
  /**
   * Inserts the markdown link into the editor and sets the focus.
   */
  insertLinkAndFocus(editor, file, sourcePath, alias, context) {
    let link = this.app.fileManager.generateMarkdownLink(file, sourcePath, "", alias).trim();
    editor.replaceRange(link, context.start, context.end);
    const newCursorPos = {
      line: context.start.line,
      ch: context.start.ch + link.length
    };
    editor.setCursor(newCursorPos);
    editor.focus();
  }
};

// src/main.ts
var ObjectsPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    /** Current configuration of the plugin */
    this.settings = DEFAULT_SETTINGS;
  }
  /**
   * Initializes the plugin when loaded into Obsidian.
   */
  async onload() {
    await this.loadSettings();
    this.templater = new TemplaterHandler(this.app);
    this.addSettingTab(new SettingsTab(this.app, this));
    this.registerEditorSuggest(new TriggerSuggest(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.verifyIntegrations();
    });
  }
  /**
   * Checks if necessary third-party plugins (like Templater) are active.
   * Displays a notice if Templater is missing.
   */
  verifyIntegrations() {
    const api = this.templater.getApi();
    if (!api) {
      const message = 'Objects: The "Templater" plugin is not active. Please install and enable it for full functionality.';
      new import_obsidian6.Notice(message, 7e3);
    }
  }
  /**
   * Loads saved settings and merges them with default values.
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * Permanently saves current settings.
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
